### PR TITLE
PLAT-12171 lower version

### PR DESCRIPTION
**Pull request by cruz636**

### CODE REVIEW

**Review by driverdan — CHANGES_REQUESTED** [review]
Pipfile.lock wasn't properly updated. It's still using psycopg2 2.9.7.

**Comment by cruz636** [comment]
> Pipfile.lock wasn't properly updated. It's still using psycopg2 2.9.7.

This is weird. The Pipfile was updated after I ran the `pipenv install` command. However, it is pinning the wrong version as you mentioned.

**Comment by cruz636** [comment]
Version 2.9 works and also pins the correct version on the Pipfile.lock . 
Dependabot might try to update it to a major version, but  we can reject the PR. 
cc: @driverdan

**Comment by driverdan** [comment]
I think it's having a problem with that specific version. Maybe it failed to fetch the first time and cached the result?

**Pull request merged**
